//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class ActionMap
{
	Dictionary<int, Ability> actions; 
	private Unit owner;

	public ActionMap (Unit unit)
	{
		actions = new Dictionary<int, Ability>();
		owner = unit;
	}

	public void add(int id, Ability action) {
		if (actions.ContainsKey(id)) {
			throw new ArgumentException();
		}
		actions.Add(id, action);
		action.owner = owner;
	}
	
	public void use(int id, object target) {
		actions[id].use(target);
	}
	
	public bool ready(int id) {
		return actions[id].ready();
	}
	
	public void update(float dt) {
		foreach (Ability action in actions.Values) {
			action.update(dt);
		}
	}

	public float getCastTime(int id) {
		return actions[id].castTime;
	}
}